### ISSUE TITLE
Error reading the simtel MC shower on certain files

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/pyeventio#221]
Related discussion: https://github.com/cta-observatory/ctapipe/pull/1447
This seems to happen at selected events only.
In this case I used the ctapipe-stage1-tool on the  `proton_20deg_180deg_run2867___cta-prod3-demo-2147m-LaPalma-baseline.simtel.gz` file of the Prod3-Benchmark data.

>ERROR [Stage1ProcessorTool] (tool/run): Caught unexpected exception: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/core/tool.py", line 225, in run
    self.start()
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/tools/stage1.py", line 685, in start
    self._process_events(writer)
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/tools/stage1.py", line 468, in _process_events
    for event in tqdm(
  File "/home/lnickel/conda/envs/ctapipe_study/lib/python3.8/site-packages/tqdm/std.py", line 1152, in __iter__
    for obj in iterable:
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/io/eventsource.py", line 254, in __iter__
    for event in self._generator():
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/io/simteleventsource.py", line 338, in _generator
    yield from self._generate_events()
  File "/net/nfshome/home/lnickel/ctapipe/ctapipe/io/simteleventsource.py", line 355, in _generate_events
    for counter, array_event in enumerate(self.file_):
  File "/home/lnickel/conda/envs/ctapipe_study/lib/python3.8/site-packages/eventio/simtel/simtelfile.py", line 239, in iter_array_events
    self.next_low_level()
  File "/home/lnickel/conda/envs/ctapipe_study/lib/python3.8/site-packages/eventio/simtel/simtelfile.py", line 144, in next_low_level
    self.current_mc_shower = o.parse()
  File "/home/lnickel/conda/envs/ctapipe_study/lib/python3.8/site-packages/eventio/simtel/objects.py", line 1326, in parse
    mc['cmax'] = read_float(byte_stream)
  File "/home/lnickel/conda/envs/ctapipe_study/lib/python3.8/site-packages/eventio/tools.py", line 28, in read_float
    return struct.unpack('<f', f.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by LukasNickel** [comment]
30 showers are written out, namely the ones with the event ids:
>[ 30702,  30708,  30710,  30714,  48511,  69307,  73111,  77412,
       124012, 158805, 192905, 193006, 193008, 193011, 221117, 262605,
       262607, 262612, 262615, 321900, 321915, 334709, 364504, 399713,
       435313, 447603, 447615, 461901, 502002, 502009]

**Comment by maxnoe** [comment]
I think the download just failed in the middle of the file.

**Comment by maxnoe** [comment]
Yes, the file on our server has 21MB (should be several GB)

**Comment by maxnoe** [comment]
But one more error to catch in next
